namespace GiftHunt.LevelUtils
{
    internal static class LevelNameMapper
    {
        // maps level ids to their display names to be used for gift seeds
        private static readonly Dictionary<string, string> LevelIdToDisplayName = new()
        {
            { "TUT_MOVEMENT", "Movement" },
            { "TUT_SHOOTINGRANGE", "Pummel" },
            { "SLUGGER", "Gunner" },
            { "TUT_FROG", "Cascade" },
            { "TUT_JUMP", "Elevate" },
            { "GRID_TUT_BALLOON", "Bounce" },
            { "TUT_BOMB2", "Purify" },
            { "TUT_BOMBJUMP", "Climb" },
            { "TUT_FASTTRACK", "Fasttrack" },
            { "GRID_PORT", "GlassPort" },
            { "GRID_PAGODA", "TakeFlight" },
            { "TUT_RIFLE", "Godspeed" },
            { "TUT_RIFLEJOCK", "Dasher" },
            { "TUT_DASHENEMY", "Thrasher" },
            { "GRID_JUMPDASH", "Outstretched" },
            { "GRID_SMACKDOWN", "Smackdown" },
            { "GRID_MEATY_BALLOONS", "Catwalk" },
            { "GRID_FAST_BALLOON", "Fastlane" },
            { "GRID_DRAGON2", "Distinguish" },
            { "GRID_DASHDANCE", "Dancer" },
            { "TUT_GUARDIAN", "Guardian" },
            { "TUT_UZI", "Stomp" },
            { "TUT_JUMPER", "Jumper" },
            { "TUT_BOMB", "DashTower" },
            { "GRID_DESCEND", "Descent" },
            { "GRID_STAMPEROUT", "Driller" },
            { "GRID_CRUISE", "Canals" },
            { "GRID_SPRINT", "Sprint" },
            { "GRID_MOUNTAIN", "Mountain" },
            { "GRID_SUPERKINETIC", "Superkinetic" },
            { "GRID_ARRIVAL", "Arrival" },
            { "FLOATING", "ForgottenCity" },
            { "GRID_BOSS_YELLOW", "TheClocktower" },
            { "GRID_HOPHOP", "Fireball" },
            { "GRID_RINGER_TUTORIAL", "Ringer" },
            { "GRID_RINGER_EXPLORATION", "Cleaner" },
            { "GRID_HOPSCOTCH", "Warehouse" },
            { "GRID_BOOM", "Boom" },
            { "GRID_SNAKE_IN_MY_BOOT", "Streets" },
            { "GRID_FLOCK", "Steps" },
            { "GRID_BOMBS_AHOY", "Demolition" },
            { "GRID_ARCS", "Arcs" },
            { "GRID_APARTMENT", "Apartment" },
            { "TUT_TRIPWIRE", "HangingGardens" },
            { "GRID_TANGLED", "Tangled" },
            { "GRID_HUNT", "Waterworks" },
            { "GRID_CANNONS", "Killswitch" },
            { "GRID_FALLING", "Falling" },
            { "TUT_SHOCKER2", "Shocker" },
            { "TUT_SHOCKER", "Bouquet" },
            { "GRID_PREPARE", "Prepare" },
            { "GRID_TRIPMAZE", "Triptrack" },
            { "GRID_RACE", "Race" },
            { "TUT_FORCEFIELD2", "Bubble" },
            { "GRID_SHIELD", "Shield" },
            { "SA L VAGE2", "Overlook" },
            { "GRID_VERTICAL", "Pop" },
            { "GRID_MINEFIELD", "Minefield" },
            { "TUT_MIMIC", "Mimic" },
            { "GRID_MIMICPOP", "Trigger" },
            { "GRID_SWARM", "Greenhouse" },
            { "GRID_SWITCH", "Sweep" },
            { "GRID_TRAPS2", "Fuse" },
            { "TUT_ROCKETJUMP", "HeavensEdge" },
            { "TUT_ZIPLINE", "Zipline" },
            { "GRID_CLIMBANG", "Swing" },
            { "GRID_ROCKETUZI", "Chute" },
            { "GRID_CRASHLAND", "Crash" },
            { "GRID_ESCALATE", "Ascent" },
            { "GRID_SPIDERCLAUS", "Straightaway" },
            { "GRID_FIRECRACKER_2", "Firecracker" },
            { "GRID_SPIDERMAN", "Streak" },
            { "GRID_DESTRUCTION", "Mirror" },
            { "GRID_HEAT", "Escalation" },
            { "GRID_BOLT", "Bolt" },
            { "GRID_PON", "Godstreak" },
            { "GRID_CHARGE", "Plunge" },
            { "GRID_MIMICFINALE", "Mayhem" },
            { "GRID_BARRAGE", "Barrage" },
            { "GRID_1GUN", "Estate" },
            { "GRID_HECK", "Trapwire" },
            { "GRID_ANTFARM", "Ricochet" },
            { "GRID_FORTRESS", "Fortress" },
            { "GRID_GODTEMPLE_ENTRY", "HolyGround" },
            { "GRID_BOSS_GODSDEATHTEMPLE", "TheThirdTemple" },
            { "GRID_EXTERMINATOR", "Spree" },
            { "GRID_FEVER", "Breakthrough" },
            { "GRID_SKIPSLIDE", "Glide" },
            { "GRID_CLOSER", "Closer" },
            { "GRID_HIKE", "Hike" },
            { "GRID_SKIP", "Switch" },
            { "GRID_CEILING", "Access" },
            { "GRID_BOOP", "Congregation" },
            { "GRID_TRIPRAP", "Sequence" },
            { "GRID_ZIPRAP", "Marathon" },
            { "TUT_ORIGIN", "Sacrifice" },
            { "GRID_BOSS_RAPTURE", "Absolution" },
            { "SIDEQUEST_OBSTACLE_PISTOL", "ElevateTraversalI" },
            { "SIDEQUEST_OBSTACLE_PISTOL_SHOOT", "ElevateTraversalII" },
            { "SIDEQUEST_OBSTACLE_MACHINEGUN", "PurifyTraversal" },
            { "SIDEQUEST_OBSTACLE_RIFLE_2", "GodspeedTraversal" },
            { "SIDEQUEST_OBSTACLE_UZI2", "StompTraversal" },
            { "SIDEQUEST_OBSTACLE_SHOTGUN", "FireballTraversal" },
            { "SIDEQUEST_OBSTACLE_ROCKETLAUNCHER", "DominionTraversal" },
            { "SIDEQUEST_RAPTURE_QUEST", "BookOfLifeTraversal" },
            { "SIDEQUEST_DODGER", "Doghouse" },
            { "GRID_GLASSPATH", "Choker" },
            { "GRID_GLASSPATH2", "Chain" },
            { "GRID_HELLVATOR", "Hellevator" },
            { "GRID_GLASSPATH3", "Razor" },
            { "SIDEQUEST_ALL_SEEING_EYE", "AllSeeingEye" },
            { "SIDEQUEST_RESIDENTSAWB", "ResidentSawI" },
            { "SIDEQUEST_RESIDENTSAW", "ResidentSawII" },
            { "SIDEQUEST_SUNSET_FLIP_POWERBOMB", "SunsetFlipPowerbomb" },
            { "GRID_BALLOONLAIR", "BalloonMountain" },
            { "SIDEQUEST_BARREL_CLIMB", "ClimbingGym" },
            { "SIDEQUEST_FISHERMAN_SUPLEX", "FishermanSuplex" },
            { "SIDEQUEST_STF", "STF" },
            { "SIDEQUEST_ARENASIXNINE", "Arena" },
            { "SIDEQUEST_ATTITUDE_ADJUSTMENT", "AttitudeAdjustment" },
            { "SIDEQUEST_ROCKETGODZ", "Rocket" },
            { "SIDEQUEST_GREEN_MEMORY", "GreenMemoryI" },
            { "SIDEQUEST_GREEN_MEMORY_2", "GreenMemoryII" },
            { "SIDEQUEST_GREEN_MEMORY_3", "GreenMemoryIII" },
            { "SIDEQUEST_GREEN_MEMORY_4", "GreenMemoryIV" },
        };

        private static readonly Dictionary<string, string> LevelDisplayNameToId = LevelIdToDisplayName
            .ToDictionary(pair => pair.Value, pair => pair.Key);

        public static string GetDisplayName(string levelId)
        {
            return LevelIdToDisplayName.TryGetValue(levelId, out string name) ? name : null;
        }

        public static string GetLevelId(string levelName)
        {
            return LevelDisplayNameToId.TryGetValue(levelName, out string Id) ? Id : null;
        }
    }
}
